org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.233
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=neoecoae
mod_name=Neo ECO AE Extension
mod_license=GPLv3
mod_version=21.2.0
mod_group_id=cn.dancingsnow.neoecoae
mod_authors=DancingSnow, ZhuRuoLing
mod_description=Neo ECO AE Extension is an addon for Applied Energistics 2, Provides higher-performance components

## dependency
jei_version=19.27.0.340
emi_version=1.1.22+1.21.1
yoga_version=1.0.0
taffy_version=1.1.3
ldlib2_version=2.2.8
kubejs_version=2101.7.2-build.353
geckolib_version=4.8.3
